import studiotattoo from "./images/studiotattoo.jpeg";
import logiatatto from "./images/logia-tattoo.png";
import studioTattooWhite from "./images/studio-tattoo-white.jpeg";
import tattooStudioGold from "./images/tattoo-studio-gold.jpeg";

export const data = [
  {
    placeId: "ChIJ-VWueX-ipBIRf3fFU39Hob8",
    name: "Logia Tattoo",
    address: "Carrer de Tarragona, 84, 08015 Barcelona",
    score: 4.5,
    logo: logiatatto,
    city: "Barcelona",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJq4zoWHeipBIRkkVKEYWQZ4g",
    name: "Ondo Tattoo",
    address: "Carrer dels Morabos, 24, Local 2, 08004 Barcelona",
    score: 4,
    logo: studiotattoo,
    city: "Barcelona",
    styles: [
      "Color",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
    ],
  },
  {
    placeId: "ChIJj0O7Uf-ipBIRvhFLxiqJUj4",
    name: "Family Art Tattoo",
    address: "Carrer del Regomir, 18-22, Local, 08002 Barcelona",
    score: 4.9,
    logo: studioTattooWhite,
    city: "Barcelona",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Black & Grey",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJ1Usm46OipBIRblYR3ljOHXE",
    name: "Sacrifice Tattoo",
    address: "Avinguda de la Riera de Cassoles, 64, 08012 Barcelona",
    score: 4.8,
    logo: tattooStudioGold,
    city: "Barcelona",
    styles: [
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Watercolor",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJH5-DD5aipBIRSuazj0pIlZk",
    name: "Eclipse Tattoo",
    address: "Carrer del Torrent de l'Olla, 53, 08012 Barcelona",
    score: 4.8,
    logo: "",
    city: "Barcelona",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Microrealismo",
      "Blackwork",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJ90tuX7yipBIRRDAZOmo2oVY",
    name: "Gold Street Tattoo",
    address: "Carrer de l'Or, 36, 08012 Barcelona",
    score: 4.5,
    logo: logiatatto,
    city: "Barcelona",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Blackwork",
      "Lettering",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJZfaMTvWipBIR6qcXXBTsa2I",
    name: "Siha Tattoo",
    address: "Carrer de Ferlandina, 32, 08001 Barcelona",
    score: 4.5,
    logo: logiatatto,
    city: "Barcelona",
    styles: [
      "Anime",
      "Tradicional",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJwWO9FvSipBIRxu79PsHn1Uw",
    name: "LTW Tattoo & Piercing",
    address: "Carrer dels Tallers, 29, 08001 Barcelona",
    score: 4.6,
    logo: studiotattoo,
    city: "Barcelona",
    styles: [
      "Japanese",
      "Ilustrativo",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJd6rtFPaipBIR_T61WS3nNH0",
    name: "Barna Tattoo",
    address: "La Rambla, 40, 08001 Barcelona",
    score: 4.9,
    logo: studiotattoo,
    city: "Barcelona",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJPewP7fyipBIRSAI7SVN6UAU",
    name: "Barcelona Elèctric Tattoo",
    address: "Carrer del Portal Nou, 29, 08003 Barcelona",
    score: 3.5,
    logo: "",
    city: "Barcelona",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJT5YcCqMvQg0RJZSstc6r2eo",
    name: "Acme Tattoo Studio",
    address: "C. del Canal del Bósforo, 6, 28022 Madrid",
    score: 4.7,
    logo: logiatatto,
    city: "Madrid",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJmUEGm2EoQg0RyTXVfZ5ZyFI",
    name: "La Manuela Tattoo",
    address: "Calle del Divino Pastor, 8, 28004 Madrid",
    score: 4.2,
    logo: logiatatto,
    city: "Madrid",
    styles: [
      "Color",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
    ],
  },
  {
    placeId: "ChIJvQovOogoQg0RDsZxjbGCodE",
    name: "Mao & Cathy",
    address: "Corre. Alta de San Pablo, 6, 28004 Madrid",
    score: 4.6,
    logo: "",
    city: "Madrid",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Black & Grey",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJHQlB_gAnQg0ReTA5bjIivKU",
    name: "JuanPe Tattoo",
    address: "C. Jayena, 7, 28041 Madrid",
    score: 4.5,
    logo: logiatatto,
    city: "Madrid",
    styles: [
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Watercolor",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJT_YxC2IoQg0R-EMdhQXDSP8",
    name: "True Love Tattoo",
    address: "C. de Velarde, 22, 28004 Madrid",
    score: 4.7,
    logo: logiatatto,
    city: "Madrid",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Microrealismo",
      "Blackwork",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJ907GVIYoQg0RfwBl6iRZtGo",
    name: "Tattoo Magic",
    address: "C. de las Infantas, 8, 28004 Madrid",
    score: 3.2,
    logo: "",
    city: "Madrid",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Blackwork",
      "Lettering",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJtx5PmFEpQg0R7CQ2blRja0s",
    name: "Estigma Tattoo",
    address: "C. de Valverde, 26, 28004 Madrid",
    score: 4.4,
    logo: logiatatto,
    city: "Madrid",
    styles: [
      "Anime",
      "Tradicional",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJT_-us9cnQg0RudP5JoJqMrw",
    name: "Ink Sweet Tattoo",
    address: "C. de Ote., 1, 28005 Madrid",
    score: 4.5,
    logo: studiotattoo,
    city: "Madrid",
    styles: [
      "Japanese",
      "Ilustrativo",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJwaX1Tn0nQg0RR79BdefWYUM",
    name: "Baltasar Tattoo Studio",
    address: "C. de San Alejandro, 6, 28005 Madrid",
    score: 4.8,
    logo: logiatatto,
    city: "Madrid",
    styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Black & Grey",
      "Sketch",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
  {
    placeId: "ChIJjxtEk4koQg0RzRutZSOGfbY",
    name: "La Mano Zurda",
    address: "Calle de Apodaca, 1, 28004 Madrid",
    score: 4.9,
    logo: studiotattoo,
    city: "Madrid",
    Styles: [
      "Anime",
      "Tradicional",
      "Japanese",
      "Ilustrativo",
      "Blackout",
      "Color",
      "Microrealismo",
      "Blackwork",
      "Lettering",
      "Ornamental",
      "Realismo",
      "Watercolor",
      "Fineline",
      "Puntillismo",
      "Neotradicional",
      "New School",
      "Minimalismo",
      "Geometrico",
    ],
  },
];
